"""Fetch, unpack and check a Studio task.

    python3 tasks/studio.py har    <file.har>              # extension capture or DevTools HAR
    python3 tasks/studio.py unpack <task-export.json>      # -> tasks/<task-id>/studio/
    python3 tasks/studio.py check  <task-export.json | tasks/<task-id>>
    python3 tasks/studio.py rules  <tasks/<task-id>/studio/qc-specs.json>   # -> docs/10-autoqc-rules.md
    python3 tasks/studio.py form   <tasks/<task-id>/studio/form-schema.json> # -> docs/11-annotation-form.md

`har` reads a sanitized HAR recorded on the task page (docs/09-studio-flow.md
§2.1) and writes every piece of the task the page loaded: the task and rubrics
(then runs `unpack`), bundle files into harbor/, transcripts and logs into
trajectories/, reviewer comments, history, AutoQC audits and QC specs into
studio/. Signed download URLs are never written.

`unpack` copies the export into tasks/<task-id>/studio/export.json and writes
readable files beside it: meta.md, prompt.md, patch_a.diff, patch_b.diff,
final_answer_a.md, final_answer_b.md and annotation-current.md. Re-run it on
every fresh export; it overwrites studio/ and touches nothing else.

`check` applies the rules Studio's own "How this task works" page, Navigation
checklist and QC notes state (docs/09-studio-flow.md). BLOCK lines stop a
submission. WARN lines are judgment calls. Like gate.py, it cannot tell whether a
reason is true.

What an export does NOT contain: the trajectories (only S3 links), the task
bundle (environment/, solution/, tests/), AutoQC results and reviewer feedback.
docs/09-studio-flow.md §2 says how to fetch those.
"""

import base64
import json
import re
import shutil
import sys
from pathlib import Path
from urllib.parse import urlsplit

sys.path.insert(0, str(Path(__file__).resolve().parent))
import prose  # noqa: E402  (same directory)

REPO = Path(__file__).resolve().parent.parent
DIMENSIONS = {
    2: "Architecture, Modularity & Trade-off Soundness",
    3: "Codebase Conventions & Utility Reuse",
    4: "Robustness, Safety & API Stability",
    5: "Instruction Following & Scope Discipline",
    6: "Planning, Research & Tool Proficiency",
    7: "Verification & Testing Discipline",
    8: "Intermediate Communication & Risk Explanation",
    9: "Final Summary & Presentation Quality",
}
STATUSES = {"PASS", "PARTIAL", "FAIL"}
PREFERENCES = {"A_MUCH_BETTER", "A_BETTER", "TIE", "B_BETTER", "B_MUCH_BETTER"}
# Custom-field ids Studio uses for the pairwise verdict (identical across exports seen).
F_RATIONALE = "field_1e32bd048d564685ba8ec51f9af11c70"
F_PREFERENCE = "field_e511999a150a45c2b7145f808103d78c"
RUBRIC_MIN, RUBRIC_MAX = 8, 15
PASS_RATE_LIMIT = 0.75  # QC note: each side's rubric YES rate strictly below 75%
OTHER_SIDE = {"a": re.compile(r"\b(side B|B's|model B|trajectory B)\b"),
              "b": re.compile(r"\b(side A|A's|model A|trajectory A)\b")}


# ------------------------------------------------------------------------ loading
def load(path):
    path = Path(path)
    if path.is_dir():
        path = path / "studio" / "export.json"
    return json.loads(path.read_text(encoding="utf-8")), path


def slug(task):
    cf = task["custom_fields"]
    return (cf.get("field_task_id") or task["task_name"]).split("#")[0].strip()


def rubrics(task):
    cf = task["custom_fields"]
    criteria = {v["verifier_index"] + 1: v["config_input"].get("criteria", "")
                for v in task.get("task_verifiers", [])
                if v.get("config_id") == "evalcfg_prompt_specific_rubric"}
    nums = sorted({int(m.group(1)) for k in cf
                   if (m := re.match(r"field_ta_rubric_(\d+)_", k))} | set(criteria))
    out = []
    for n in nums:
        p = f"field_ta_rubric_{n:02d}_"
        out.append({
            "n": n, "criteria": criteria.get(n, ""),
            **{f"{f}_{s}": cf.get(f"{p}{f}_{s}") for f in ("answer", "reason", "mapped_dimension")
               for s in "ab"},
        })
    return out


def dims(task, side):
    cf = task["custom_fields"]
    return {d: (cf.get(f"field_ta_dim{d}_score_{side}"), cf.get(f"field_ta_dim{d}_reason_{side}"))
            for d in DIMENSIONS}


# ------------------------------------------------------------------------- unpack
def unpack(export_path):
    task, src = load(export_path)
    cf = task["custom_fields"]
    out = REPO / "tasks" / slug(task) / "studio"
    out.mkdir(parents=True, exist_ok=True)
    for sub in ("harbor", "trajectories"):
        (out.parent / sub).mkdir(exist_ok=True)
    if src.resolve() != (out / "export.json").resolve():
        shutil.copyfile(src, out / "export.json")

    def files(key):
        return ", ".join(f"{f['file_title']} ({f['file_s3_url']})" for f in cf.get(key) or []) or "—"

    meta = [
        f"# {task['task_name']}", "",
        "Generated by `tasks/studio.py unpack` from `export.json`. Don't edit; re-run instead.", "",
        "| Field | Value |", "|---|---|",
    ]
    rows = [
        ("Task ID", cf.get("field_task_id")), ("Studio task id", task["task_id"]),
        ("Task version", task.get("task_version")), ("Updated at", task.get("updated_at")),
        ("Task type", cf.get("field_task_type")), ("Task format", cf.get("field_task_format")),
        ("Language / category", cf.get("field_language")), ("Difficulty", cf.get("field_difficulty")),
        ("Repository", cf.get("field_repo_url")), ("Harness", cf.get("field_harness")),
        ("Model A", cf.get("field_model_a")), ("Model B", cf.get("field_model_b")),
        ("Gemini side", cf.get("field_gemini_side")),
        ("Recorded score A / B", f"{cf.get('field_score_a')} / {cf.get('field_score_b')}"),
        ("Dimension 0 seeded A / B", f"{cf.get('field_part1_a')} / {cf.get('field_part1_b')}"),
        ("Dimension 0 disposition", cf.get("field_part1_disposition")),
        ("Patch A provenance", cf.get("field_patch_a_provenance") or "captured diff"),
        ("Patch B provenance", cf.get("field_patch_b_provenance") or "captured diff"),
        ("Transcript A", files("transcript_file_a")), ("Transcript B", files("transcript_file_b")),
        ("Artifacts A", files("artifact_files_a")), ("Artifacts B", files("artifact_files_b")),
    ]
    meta += [f"| {k} | {str(v).replace('|', '\\|') if v not in (None, '') else '—'} |" for k, v in rows]
    for key, title in (("field_part1_reason", "Dimension 0 check"),
                       ("field_part1_reason_a", "Dimension 0 check, A"),
                       ("field_part1_reason_b", "Dimension 0 check, B"),
                       ("field_adj_rationale", "QC / reviewer note"),
                       ("field_dl_run_ledger", "Run ledger")):
        if cf.get(key):
            meta += ["", f"## {title}", "", str(cf[key])]
    (out / "meta.md").write_text("\n".join(meta) + "\n", encoding="utf-8")

    prompt = cf.get("field_task_prompt") or (
        "_The export carries no prompt for this task. Terminal-bench tasks keep it in "
        "`harbor/instruction.md`; fetch the bundle (docs/09-studio-flow.md §2)._")
    (out / "prompt.md").write_text(prompt + "\n", encoding="utf-8")
    for s in "ab":
        (out / f"patch_{s}.diff").write_text(cf.get(f"field_patch_{s}") or "", encoding="utf-8")
        (out / f"final_answer_{s}.md").write_text((cf.get(f"field_final_answer_{s}") or "") + "\n",
                                                  encoding="utf-8")

    ann = [f"# Current annotation: {cf.get('field_task_id')}", "",
           "The annotation as it stands in Studio at export time. Generated; don't edit.", ""]
    for s in "ab":
        S = s.upper()
        ann += [f"## Trajectory {S} ({cf.get(f'field_model_{s}')})", "",
                f"**Dimension 0:** {cf.get(f'field_part1_{s}')}", ""]
        for d, (score, reason) in dims(task, s).items():
            ann += [f"### {d} · {DIMENSIONS[d]}: {score!r}", "", reason or "_(no reason)_", ""]
        ann += [f"**Final quality score {S}:** {cf.get(f'field_ta_final_quality_score_{s}')!r}", ""]
    ann += ["## Rubrics", ""]
    for r in rubrics(task):
        ann += [f"### {r['n']}. {r['criteria']}", "",
                f"- Mapped dimension: A `{r['mapped_dimension_a']}` · B `{r['mapped_dimension_b']}`",
                f"- **A: {r['answer_a']}** — {r['reason_a']}",
                f"- **B: {r['answer_b']}** — {r['reason_b']}", ""]
    ann += ["## Pairwise verdict", "", f"**Preference:** {cf.get(F_PREFERENCE)}", "",
            cf.get(F_RATIONALE) or "_(no rationale)_", ""]
    (out / "annotation-current.md").write_text("\n".join(ann), encoding="utf-8")

    print(f"Unpacked to {out.relative_to(REPO)}/")
    for p in sorted(out.iterdir()):
        print(f"  {p.name}")
    print("\nNot in the export: trajectories, task bundle, AutoQC, reviewer feedback "
          "(docs/09-studio-flow.md §2).")


# ---------------------------------------------------------------------------- har
API = "api.studio.mercor.com"
S3 = "rl-studio-snapshots-prod.s3.amazonaws.com"


def har(har_path):
    log = json.loads(Path(har_path).read_text(encoding="utf-8"))["log"]
    entries = log["entries"]
    capture = log.get("_capture")  # present when the file came from tools/studio-capture
    if capture:
        print(f"Extension capture of {capture.get('task_name')} at {capture.get('captured_at')}")
        for err in capture.get("errors") or []:
            print(f"  ! capture error: {err}")
    responses = []  # (host, path, query, bytes)
    for e in entries:
        u = urlsplit(e["request"]["url"])
        c = e["response"].get("content") or {}
        if e["request"]["method"] != "GET" or e["response"]["status"] != 200 or not c.get("text"):
            continue
        raw = base64.b64decode(c["text"]) if c.get("encoding") == "base64" else c["text"].encode()
        responses.append((u.netloc, u.path, u.query, raw))

    def api(pattern):
        return [(m, raw) for host, path, _, raw in responses
                if host == API and (m := re.fullmatch(pattern, path))]

    task_ids = {m.group(1) for m, _ in api(r"/tasks/(task_[0-9a-f]{32})")}
    if not task_ids:
        sys.exit("No task found in the HAR: record it on a task page (docs/09-studio-flow.md §2.1).")
    for task_id in sorted(task_ids):
        har_task(task_id, api, responses)


def har_task(task_id, api, responses):
    def one(pattern):
        hits = [json.loads(raw) for _, raw in api(pattern)]
        return hits[-1] if hits else None

    task = one(rf"/tasks/{task_id}")
    cf = task["custom_fields"]
    verifiers = (one(rf"/verifiers/task/{task_id}") or {}).get("verifiers", [])
    task["task_verifiers"] = [{**v, "config_id": v.get("eval_config_id"),
                               "config_input": v.get("verifier_values") or {}} for v in verifiers]
    root = REPO / "tasks" / slug(task)
    studio = root / "studio"
    studio.mkdir(parents=True, exist_ok=True)
    (studio / "export.json").write_text(json.dumps(task, indent=2), encoding="utf-8")
    unpack(studio / "export.json")
    got, missing = [], []

    # Task bundle: S3 objects under the task snapshot's filesystem/
    listing = one(rf"/snapshots/task/{task_id}/input-files") or {"files": []}
    prefix = f"/tasks/{task['task_data_id']}/filesystem/"
    fetched = set()
    for host, path, _, raw in responses:
        if host == S3 and path.startswith(prefix):
            rel = path[len(prefix):]
            dest = root / "harbor" / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(raw)
            if rel not in fetched:
                got.append(f"harbor/{rel}")
            fetched.add(rel)
    for f in listing["files"]:
        rel = f["key"].split("/filesystem/", 1)[-1]
        if rel not in fetched:
            missing.append(f"harbor/{rel}: click it in tab B while recording")

    world_rubric = one(rf"/verifiers/world/{task.get('world_id')}") if task.get("world_id") else None
    if world_rubric:
        (studio / "world-rubric.json").write_text(json.dumps(world_rubric, indent=2), encoding="utf-8")
        got.append("studio/world-rubric.json")

    # Trajectories and logs, labelled A/B from the run ledger
    try:
        ledger = json.loads(cf.get("field_dl_run_ledger") or "{}")
    except json.JSONDecodeError:
        ledger = {}
    sides = {ledger[s]["trajectory_id"]: s for s in "AB" if s in ledger}
    (root / "trajectories").mkdir(exist_ok=True)
    for traj_id, side in sides.items():
        for pattern, name, hint in ((rf"/trajectories/{traj_id}", f"transcript_{side}.json",
                                     "open its Trajectory Viewer tab"),
                                    (rf"/trajectory-logs/list/{traj_id}", f"logs_{side}.json",
                                     "open LOGS and click Expand all")):
            body = one(pattern)
            if body is None:
                missing.append(f"trajectories/{name}: on Model {side}, {hint}")
                continue
            (root / "trajectories" / name).write_text(json.dumps(body, indent=2), encoding="utf-8")
            got.append(f"trajectories/{name}")
            if name.startswith("transcript_"):
                (root / "trajectories" / f"{side}.md").write_text(render_transcript(body, side),
                                                                   encoding="utf-8")
                got.append(f"trajectories/{side}.md")

        # Artifacts (the real agent.patch) live under the trajectory's own snapshot.
        snap = one(rf"/snapshots/trajectory/{traj_id}")
        for f in (snap or {}).get("files", []):
            rel = f["key"].split("/filesystem/", 1)[-1]
            dest = root / "trajectories" / f"{side.lower()}_{Path(rel).name}"
            blob = next((raw for host, path, _, raw in responses
                         if host == S3 and path.endswith(f"/{snap['snapshot_id']}/filesystem/{rel}")), None)
            if blob is None:
                missing.append(f"{dest.relative_to(root)}: capture with the extension (the page "
                               "never downloads trajectory artifacts)")
                continue
            dest.write_bytes(blob)
            got.append(f"trajectories/{dest.name}")

    # Reviewer comments, history, AutoQC
    comments = (one(rf"/inline-review-comments/task/{task_id}") or {}).get("comments", [])
    (studio / "review-comments.json").write_text(json.dumps(comments, indent=2), encoding="utf-8")
    fb = [f"# Reviewer feedback: {cf.get('field_task_id')}", "",
          "Generated by `tasks/studio.py har`. Inline review comments, oldest first.", ""]
    for c in sorted(comments, key=lambda c: c["created_at"]):
        loc = c.get("irc_location") or {}
        where = "prompt" if loc.get("is_prompt") else loc.get("custom_field_id") or loc.get("anchor_text") or "task"
        fb += [f"## {c['created_at']} · {c.get('author_role')} · on {where}", "", c["contents_string"], ""]
    if cf.get("field_adj_rationale"):
        fb += ["## QC note (field_adj_rationale)", "", cf["field_adj_rationale"], ""]
    (studio / "review-feedback.md").write_text("\n".join(fb), encoding="utf-8")
    got.append(f"studio/review-feedback.md ({len(comments)} comment(s))")

    world = one(rf"/worlds/{task.get('world_id')}") if task.get("world_id") else None
    fields = ((world or {}).get("task_schema") or {}).get("fields")
    if fields:
        (studio / "form-schema.json").write_text(json.dumps(fields, indent=2), encoding="utf-8")
        got.append(f"studio/form-schema.json ({len(fields)} form fields)")
    else:
        missing.append("studio/form-schema.json: the Studio form definition (dimension bands, "
                       "score labels, word minimums)")

    history = one(rf"/tasks/{task_id}/history")
    if history:
        (studio / "history.json").write_text(json.dumps(history, indent=2), encoding="utf-8")
        got.append(f"studio/history.json ({len(history.get('history', []))} versions)")

    audits, specs = {}, {}
    for host, path, _, raw in responses:
        if host != API:
            continue
        if path == "/qc-audits/":
            for a in json.loads(raw).get("audits", []):
                if a.get("subject_id") == task_id:
                    audits[a["qc_audit_id"]] = a
        elif path == "/qc-specs/":
            for s in json.loads(raw).get("specs", []):
                specs[s["qc_spec_id"]] = s
    if audits:
        ordered = sorted(audits.values(), key=lambda a: a["created_at"])
        (studio / "qc-audits.json").write_text(json.dumps(ordered, indent=2), encoding="utf-8")
        (studio / "autoqc.md").write_text(render_autoqc(ordered, specs, cf), encoding="utf-8")
        got.append(f"studio/autoqc.md ({len(ordered)} audit run(s))")
    else:
        missing.append("studio/autoqc.md: open Deliverable AutoQC while recording")
    if specs:
        (studio / "qc-specs.json").write_text(json.dumps(list(specs.values()), indent=2), encoding="utf-8")
        got.append(f"studio/qc-specs.json ({len(specs)} spec(s))")

    print(f"\nFrom the HAR, for {slug(task)}:")
    for g in got:
        print(f"  + {g}")
    for m in missing:
        print(f"  - missing {m}")


def render_transcript(traj, side):
    """One heading per message, numbered by its index in trajectory_messages. That
    index is what "record N" means in Studio annotations (checked 2026-09-15)."""
    msgs = traj.get("trajectory_messages", [])
    silent = sum(1 for m in msgs if m["role"] == "assistant" and not m["content"].strip())
    assistant = sum(1 for m in msgs if m["role"] == "assistant")
    empty_args = sum(1 for m in msgs for c in m.get("tool_calls") or []
                     if (c.get("function") or {}).get("arguments") in ("{}", "", None))
    out = [f"# Trajectory {side}: {traj['trajectory_id']}", "",
           f"Generated by `tasks/studio.py har`. {len(msgs)} records · {assistant} assistant turns, "
           f"{silent} with no text · {empty_args} tool calls with no recorded arguments.", ""]
    if empty_args:
        out += ["> The import kept tool **results** but not tool **arguments**, so the commands the "
                "agent ran are not recorded. Cite results, and say so when a claim depends on the "
                "command itself.", ""]
    for i, m in enumerate(msgs):
        calls = [(c.get("function") or {}).get("name") for c in m.get("tool_calls") or []]
        head = f"## [{i}] {m['role']}" + (f" → {', '.join(calls)}" if calls else "")
        text = m["content"].strip()
        if not text and m["role"] == "assistant":
            out.append(head + " _(no text)_")
            continue
        fence = "````" if "```" in text else "```"
        out += [head, "", fence if m["role"] == "tool" else "", text, fence if m["role"] == "tool" else "", ""]
    return "\n".join(out) + "\n"


def render_autoqc(audits, specs, cf):
    latest = audits[-1]
    spec = specs.get(latest["qc_spec_id"], {})
    checks = [(s["name"], d) for s in latest["outcome"].get("sections", []) for d in s.get("dimensions", [])]
    fails = [(sec, d) for sec, d in checks if d.get("status") != "pass"]
    out = [f"# AutoQC: {cf.get('field_task_id')}", "",
           "Generated by `tasks/studio.py har`. Latest audit first; older runs listed at the end.", "",
           f"**Latest run:** {latest['created_at']} · spec *{spec.get('name', latest['qc_spec_id'])}* "
           f"v{latest.get('qc_spec_version')} · task version {latest.get('subject_version')} · "
           f"{len(checks) - len(fails)}/{len(checks)} pass", "",
           "| # | Section | Check | Status | Importance | Severity |", "|---|---|---|---|---|---|"]
    for i, (sec, d) in enumerate(checks, 1):
        out.append(f"| {i} | {sec} | {d.get('dimension')} | **{d.get('status')}** | "
                   f"{d.get('importance') or '—'} | {d.get('severity') or '—'} |")
    for title, group in (("Failing checks", fails),
                         ("Passing checks", [c for c in checks if c[1].get("status") == "pass"])):
        out += ["", f"## {title}", ""]
        for sec, d in group:
            out += [f"### {d.get('dimension')} ({d.get('status')})", "", f"*{sec}*", "",
                    f"**Justification:** {d.get('justification')}", ""]
            if d.get("status") != "pass":
                if d.get("findings"):
                    out += ["**Findings:**", "", "```json", json.dumps(d["findings"], indent=2), "```", ""]
                out += ["**Analysis:**", "", d.get("analysis") or "", ""]
    out += ["", "## Earlier runs", ""]
    for a in audits[:-1]:
        sec = [d for s in a["outcome"].get("sections", []) for d in s.get("dimensions", [])]
        bad = [d.get("dimension") for d in sec if d.get("status") != "pass"]
        out.append(f"- {a['created_at']} · task version {a.get('subject_version')} · "
                   f"{len(sec) - len(bad)}/{len(sec)} pass" + (f" · failing: {'; '.join(bad)}" if bad else ""))
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------- form
def form(schema_path):
    fields = json.loads(Path(schema_path).read_text(encoding="utf-8"))
    out = ["# The Studio Annotation Form", "",
           "> **Generated by `tasks/studio.py form`** from the world's `task_schema`, which is what "
           "Studio renders. Don't edit by hand; re-run it after a capture when the form changes. "
           "The score bands below are Studio's own, and outrank the paraphrase in `docs/03`.", ""]
    groups = {}
    for f in fields:
        groups.setdefault(f.get("field_group") or "(ungrouped)", []).append(f)
    out += ["| Group | Fields |", "|---|---|"]
    out += [f"| {g} | {len(fs)} |" for g, fs in groups.items()]
    for g, fs in groups.items():
        out += ["", "---", "", f"## {g}", ""]
        for f in fs:
            bits = [f"`{f['field_id']}`", f["field_type"]]
            if f.get("required"):
                bits.append("**required**")
            if f.get("min_word_count"):
                bits.append(f"min {f['min_word_count']} words")
            for key in ("min_value", "max_value"):
                if f.get(key) is not None:
                    bits.append(f"{key} {f[key]}")
            out += ["", f"### {f['label']}", "", " · ".join(bits)]
            if f.get("options"):
                out += ["", "Options: " + ", ".join(f"`{o}`" for o in f["options"])]
            if f.get("description"):
                out += ["", f["description"]]
    dest = REPO / "docs" / "11-annotation-form.md"
    dest.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"Wrote {dest.relative_to(REPO)}: {len(fields)} fields in {len(groups)} groups")


# -------------------------------------------------------------------------- rules
# Annotator-facing specs first; the rest are task-creation and reviewer audits.
SPEC_ORDER = ["Annotation Quality QC", "Annotation Quality QC (Reviewers)",
              "Annotation Quality QC (Annotator Advisory)"]


def rules(specs_path):
    specs = json.loads(Path(specs_path).read_text(encoding="utf-8"))
    specs = sorted((s for s in specs if s.get("is_latest")),
                   key=lambda s: (SPEC_ORDER.index(s["name"]) if s["name"] in SPEC_ORDER else 99, s["name"]))
    out = ["# AutoQC Rules", "",
           "> **Generated by `tasks/studio.py rules`** from the QC specs Studio loads on a task page. "
           "Don't edit by hand; re-run it on a fresh HAR when the specs change. This is the exact text "
           "the AutoQC agents grade against, so it outranks the docs when they disagree.", "",
           "| Spec | Version | Checks | Blocking | Purpose |", "|---|---|---|---|---|"]
    body = []
    for s in specs:
        rub = s["spec"].get("rubric") or {}
        dims = [(sec.get("name"), d) for sec in rub.get("sections", []) for d in sec.get("dimensions", [])]
        blocking = sum(d.get("importance") == "blocking" for _, d in dims)
        purpose = (s.get("description") or "").replace("|", "\\|").replace("\n", " ")
        out.append(f"| [{s['name']}](#{re.sub(r'[^a-z0-9 -]', '', s['name'].lower()).replace(' ', '-')}) "
                   f"| v{s['version']} | {len(dims)} | {blocking} | {purpose} |")
        body += ["", "---", "", f"## {s['name']}", "",
                 f"v{s['version']} · {s.get('status')} · subject: {s.get('subject_kind')}", "",
                 s.get("description") or "", "", rub.get("description") or ""]
        section = None
        for sec, d in dims:
            if sec != section:
                body += ["", f"### {sec}"]
                section = sec
            body += ["", f"#### {d.get('name')}", "",
                     f"`{d.get('dim_id')}` · **{d.get('importance') or 'non-blocking'}**", "",
                     d.get("description") or ""]
            for key, label in (("pass_criteria", "Pass"), ("fail_criteria", "Fail"),
                               ("neutral_criteria", "Neutral"), ("notes", "Notes")):
                if d.get(key):
                    body += ["", f"- **{label}:** {d[key]}"]
    dest = REPO / "docs" / "10-autoqc-rules.md"
    dest.write_text("\n".join(out + body) + "\n", encoding="utf-8")
    print(f"Wrote {dest.relative_to(REPO)}: {len(specs)} specs")


# -------------------------------------------------------------------------- check
results = []
COMPOUND = re.compile(r"\b(and|or)\b|,")


def note(level, ok, message):
    results.append((level, bool(ok), message))


def block(ok, message):
    results.append(("BLOCK", bool(ok), message))


def warn(ok, message):
    results.append(("WARN", bool(ok), message))


def as_score(v):
    return v if isinstance(v, int) and not isinstance(v, bool) and 1 <= v <= 5 else None


def check(path):
    task, src = load(path)
    cf = task["custom_fields"]

    # Studio's own form rules, when a capture saved them beside the export.
    schema_file = src.parent / "form-schema.json"
    schema = {f["field_id"]: f for f in json.loads(schema_file.read_text(encoding="utf-8"))} \
        if schema_file.is_file() else {}
    ours = ("2 · Trajectory", "3 · Adjudication")  # the groups an annotator fills in
    for fid, f in schema.items():
        value = cf.get(fid)
        if not (f.get("field_group") or "").startswith(ours):
            continue
        if f.get("required") and not f.get("display_hidden") and value in (None, ""):
            warn(False, f"{fid}: required by the Studio form and still empty ({f['label']})")
        if f.get("min_word_count") and isinstance(value, str) and value.strip():
            got = len(value.split())
            block(got >= f["min_word_count"],
                  f"{fid}: at least {f['min_word_count']} words (Studio 'Length limits') — got {got}")
        if f.get("options") and isinstance(value, str) and value and value not in f["options"] \
                and f["field_type"] != "likert_scale":
            warn(False, f"{fid}: value {value!r} is not one of {f['options']}")

    # Pair eligibility and Dimension 0
    gemini = cf.get("field_gemini_side")
    block(gemini in ("A", "B"), f"a Gemini trajectory is in the pair (gemini side: {gemini!r})")
    seeds = {s: cf.get(f"field_part1_{s}") for s in "ab"}
    block(all(v in STATUSES for v in seeds.values()), f"Dimension 0 set for both sides — got {seeds}")
    block(not all(v == "FAIL" for v in seeds.values()), "not both Dimension 0 FAIL (ineligible pair)")
    disposition = cf.get("field_part1_disposition")
    # Not an AutoQC gate since spec v10 ("upstream seed faults are left to the reviewer
    # audit"), but the Task Auditor checklist still rejects a both-FAIL pair.
    warn(disposition != "REJECT_BOTH_FAIL",
         f"Dimension 0 automated check does not say REJECT_BOTH_FAIL (got {disposition!r}) — "
         "if it does, verify the grading and ask before annotating an ineligible pair")
    for s in "ab":
        score = cf.get(f"field_score_{s}")
        warn(not (score == 0.0 and seeds[s] in ("PASS", "PARTIAL")),
             f"{s.upper()}: Dimension 0 {seeds[s]} agrees with the recorded score {score}")
        prov = cf.get(f"field_patch_{s}_provenance") or ""
        warn("reconstructed" not in prov,
             f"{s.upper()}: patch is a captured diff, not reconstructed from tool calls "
             "(reconstructed hunks and missing shell edits are harness artifacts, not agent behavior)")

    # Reason prose: LLM tells and the evidence rule (tasks/prose.py, docs/12)
    reasons = [(f"{s.upper()} dim {d}", cf.get(f"field_ta_dim{d}_reason_{s}"))
               for s in "ab" for d in DIMENSIONS]
    reasons += [(f"rubric {r['n']} {s.upper()}", r[f"reason_{s}"]) for r in rubrics(task) for s in "ab"]
    reasons.append(("comparative rationale", cf.get(F_RATIONALE)))
    for tag, text in reasons:
        for sev, cid, label, fix, _line, hit in prose.check_reason(text or ""):
            note(sev if cid != "em-dash" else "WARN", False,
                  f"{tag}: {label} — {hit!r}; {fix}" if cid != "no-evidence"
                  else f"{tag}: {label}; {fix}")

    # Dimensions 2-9 and final score
    final = {}
    for s in "ab":
        S = s.upper()
        for d, (score, reason) in dims(task, s).items():
            block(as_score(score) is not None,
                  f"{S} dim {d}: score is an integer 1-5 (a string like '3' shows as required in "
                  f"Studio's Navigation; re-select it) — got {score!r}")
            block(bool(reason and reason.strip()), f"{S} dim {d}: has a reason")
            if reason:
                warn(not OTHER_SIDE[s].search(reason),
                     f"{S} dim {d}: reason judges {S} on its own merits (no reference to the other side)")
        final[s] = as_score(cf.get(f"field_ta_final_quality_score_{s}"))
        block(final[s] is not None, f"{S}: final quality score is an integer 1-5 — "
                                    f"got {cf.get(f'field_ta_final_quality_score_{s}')!r}")
        scores = [as_score(v[0]) for v in dims(task, s).values()]
        if final[s] and all(scores):
            mean = sum(scores) / len(scores)
            warn(abs(final[s] - mean) <= 1, f"{S}: final score {final[s]} is within 1 of the "
                                            f"dimension mean {mean:.2f}")

    # Rubrics
    rs = rubrics(task)
    count = cf.get("field_rubric_count")
    block(RUBRIC_MIN <= len(rs) <= RUBRIC_MAX, f"{RUBRIC_MIN}-{RUBRIC_MAX} rubrics — got {len(rs)}")
    block(str(count) == str(len(rs)), f"Rubric count ({count!r}) matches the rubrics written ({len(rs)})")
    yes = {"a": 0, "b": 0}
    for r in rs:
        tag = f"rubric {r['n']}"
        block(bool(r["criteria"].strip()), f"{tag}: has criteria text")
        warn(not COMPOUND.search(r["criteria"]),
             f"{tag}: one independently gradable proposition (AutoQC aq_a1 fails a statement whose "
             f"parts could get different answers) — review: {r['criteria']!r}")
        for s in "ab":
            block(r[f"answer_{s}"] in ("YES", "NO"), f"{tag} {s.upper()}: answered YES/NO")
            block(bool((r[f"reason_{s}"] or "").strip()), f"{tag} {s.upper()}: has a reason")
            yes[s] += r[f"answer_{s}"] == "YES"
            if r[f"reason_{s}"]:
                warn(not OTHER_SIDE[s].search(r[f"reason_{s}"]),
                     f"{tag} {s.upper()}: reason cites this side's evidence, not the other side's")
        md = {s: str(r[f"mapped_dimension_{s}"] or "") for s in "ab"}
        block(all(v.isdigit() and int(v) in DIMENSIONS for v in md.values()),
              f"{tag}: mapped to one of dimensions 2-9 — got {md}")
        block(md["a"] == md["b"], f"{tag}: same mapped dimension on both sides")
    if rs:
        for s in "ab":
            rate = yes[s] / len(rs)
            who = ("Gemini side, AutoQC aq_a4" if s.upper() == gemini
                   else "non-Gemini side, reviewer comment")
            block(rate < PASS_RATE_LIMIT, f"{s.upper()} ({who}): rubric YES rate below 75% — "
                                          f"{yes[s]}/{len(rs)} = {rate:.0%}")
        warn(any(r["answer_a"] != r["answer_b"] for r in rs), "at least one rubric separates A from B")

    # Pairwise verdict
    pref = cf.get(F_PREFERENCE)
    block(pref in PREFERENCES, f"preference is one of {sorted(PREFERENCES)} — got {pref!r}")
    block(bool((cf.get(F_RATIONALE) or "").strip()), "comparative rationale is written")
    if pref in PREFERENCES and final["a"] and final["b"]:
        gap = final["a"] - final["b"]
        side = "A" if gap > 0 else "B"
        expected = "TIE" if gap == 0 else f"{side}_BETTER" if abs(gap) == 1 else f"{side}_MUCH_BETTER"
        block(pref == expected, f"preference is exactly the label the final-score gap maps to "
                                f"(AutoQC aq_c1: A {final['a']} − B {final['b']} = {gap} → {expected}) "
                                f"— got {pref}")

    if cf.get("field_adj_rationale"):
        warn(False, f"QC / reviewer note to address: {cf['field_adj_rationale']}")

    blocked = warns = 0
    for level, ok, message in results:
        blocked += level == "BLOCK" and not ok
        warns += level == "WARN" and not ok
        print(f"{'PASS' if ok else level:5}  {message}")
    print(f"\n{blocked} blocking, {warns} warnings — {'DO NOT SUBMIT' if blocked else 'ok to submit'}")
    print("Not checkable here: whether each reason is true, AutoQC's judgment checks "
          "(docs/10-autoqc-rules.md), and anything only the trajectories or the bundle show.")
    sys.exit(1 if blocked else 0)


def main():
    commands = {"har": har, "unpack": unpack, "check": check, "rules": rules, "form": form}
    if len(sys.argv) != 3 or sys.argv[1] not in commands:
        sys.exit(__doc__)
    commands[sys.argv[1]](sys.argv[2])


if __name__ == "__main__":
    main()
